version: '3.8'
services:
  postgres:
    image: arm64v8/postgres:15-alpine
    restart: always
    ports:
      - '5532:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nodejs-template-project
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nodejs-template-project
